// ==========================================
// BASE DE DATOS DE PRODUCTOS - SENABELLA
// ==========================================

import imgZapatos from "../assets/zapatos.jpg";
import imgPareja from "../assets/pareja.jpeg";
import imgCamisa1 from "../assets/camisa_1.jpg";
import imgCamisa2 from "../assets/camisa_2.jpg";

// ==========================================
// 1. PRODUCTOS DESTACADOS (INICIO)
// ==========================================
export const productosInicio = [
  {
    id: "ini-1",
    nombre: "Cámara digital",
    precio: "$ 1.299.900",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6v1HiWNeKzYFIctVnOkEp9OtNfTmGEj1MNsNhXed1vQ&s=10",
    descuento: "-15%",
    categoria: "tecno",
  },
  {
    id: "ini-2",
    nombre: "PlayStation 4",
    precio: "$ 3.999.900",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn8UWZ26nTqWpCzbzjgGJU_NAVvXz8R8f0GvMHIz4FdA&s=10",
    nuevo: true,
    categoria: "tecno",
  },
  {
    id: "ini-3",
    nombre: "Tableta gráfica digital",
    precio: "$ 2.657.900",
    imagen:
      "https://media.falabella.com/falabellaCO/119583403_01/w=276,h=276,fit=pad",
    categoria: "tecno",
  },
  {
    id: "ini-4",
    nombre: "Audifonos Xiaomi Redmi Buds 8 Lite",
    precio: "$107.750",
    imagen:
      "https://media.falabella.com/falabellaCO/155500313_01/w=1200,h=1200,fit=pad",
    descuento: "-30%",
    categoria: "tecno",
  },
];

export const productosDestacados = productosInicio;

// ==========================================
// 2. PRODUCTOS DE TECNOLOGÍA (CATÁLOGO)
// ==========================================
export const productosCatalogo = [
  {
    id: 1,
    marca: "LENOVO",
    nombre: "Kindle paperwhite 2024 32gb 7\" Signature Edition Negra",
    referencia: "por pctel computo",
    precio: "$ 979.900",
    precioNumero: 979900,
    precioSecundario: "$ 1.019.000",
    precioSecundario1: "$ 1.399.000",
    descuento: "-30%",
    imagen: "https://media.falabella.com/falabellaCO/142972175_01/w=1200,h=1200,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 2,
    marca: "HP",
    nombre: "Impresora Multifuncional Smart Tank 585 Wifi + resma",
    referencia: "Por TS ONLINE",
    precio: "$ 679.900",
    precioNumero: 679900,
    precioSecundario: "$ 709.900",
    precioSecundario1: "$ 1.199.000",
    descuento: "-43%",
    imagen: "https://media.falabella.com.co/falabellaCO/137155110_01/width=480,height=480,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 3,
    marca: "HP",
    nombre: "Portátil 15.6\" Full HD AMD Ryzen 7 7730U 16GB RAM 512GB SSD Plata",
    referencia: "Por Compumarket Bga",
    precio: "$ 1.979.900",
    precioNumero: 1979900,
    precioSecundario: "$ 2.099.900",
    precioSecundario1: "$ 3.699.780",
    descuento: "-46%",
    imagen: "https://media.falabella.com.co/falabellaCO/127619968_01/width=480,height=480,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
    envioGratis: true,
    promocion: "NUEVO - REPOTENCIADO",
  },
  {
    id: 4,
    marca: "STARLINK",
    nombre: "Kit de internet satelital estándar V4",
    referencia: "Por SENABELLA",
    precio: "$ 1.599.000",
    precioNumero: 1599000,
    precioSecundario: "$ 2.790.000",
    precioSecundario1: "$ 3.599.900",
    descuento: "-44%",
    imagen: "https://media.falabella.com.co/falabellaCO/73053329_1/width=340,height=340,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
    verificado: true,
  },
  {
    id: 5,
    marca: "HP",
    nombre: "Portátil HP 15-Fc0276La Amd Ryzen7 7730U 8Cores/16Gb/ 1Tb Ssd/Fhd 15.6/ Plateado Natural Win11 1.59Kg",
    referencia: "Por SENABELLA",
    precio: "$ 279.900",
    precioNumero: 279900,
    precioSecundario: "$ 299.900",
    precioSecundario1: "$ 599.900",
    descuento: "-53%",
    imagen: "https://media.falabella.com.co/falabellaCO/73354813_01/width=340,height=340,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 6,
    marca: "LENOVO",
    nombre: "Tablet Lenovo Tab Plus 8GB RAM 128GB / 8 Speakers / Funda + auriculares Moto Buds - Gris",
    referencia: "Lenovo asia pacific limited sucursal colombia",
    precio: "$ 809.900",
    precioNumero: 809900,
    precioSecundario: "$ 849.900",
    precioSecundario1: "$ 1.999.900",
    descuento: "-60%",
    imagen: "https://media.falabella.com.co/falabellaCO/139001771_01/width=480,height=480,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 7,
    marca: "HP",
    nombre: "Impresora Multifuncional HP Smart Tank 585 Wifi + resma",
    referencia: "por ts online",
    precio: "$ 679.900",
    precioNumero: 679900,
    precioSecundario: "$ 709.900",
    precioSecundario1: "$ 1.199.000",
    descuento: "-43%",
    imagen: "https://media.falabella.com.co/falabellaCO/134370606_01/width=480,height=480,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 8,
    marca: "TOSHIBA",
    nombre: "Disco duro externo 2tb toshiba usb 3.0 + estuche",
    referencia: "por lapto partes",
    precio: "$ 429.210",
    precioNumero: 429210,
    precioSecundario: "$ 476.900",
    precioSecundario1: "$ 550.000",
    descuento: "-22%",
    imagen: "https://media.falabella.com/falabellaCO/124164429_01/w=1200,h=1200,fit=pad",
    etiqueta: "CYBER",
    verificado: true,
  },
  {
    id: 9,
    marca: "DELL",
    nombre: "Portátil Dell Inspiron 15 3520 Intel Core i5 16GB RAM 512GB SSD 15.6\"",
    referencia: "Por SENABELLA",
    precio: "$ 2.199.900",
    precioNumero: 2199900,
    precioSecundario: "$ 2.399.900",
    precioSecundario1: "$ 3.299.900",
    descuento: "-35%",
    imagen: "https://media.falabella.com.co/falabellaCO/127619968_01/width=480,height=480,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 10,
    marca: "ASUS",
    nombre: "Portátil Gamer ASUS TUF Gaming F15 Intel Core i7 16GB RAM RTX 3050",
    referencia: "Por SENABELLA",
    precio: "$ 3.899.900",
    precioNumero: 3899900,
    precioSecundario: "$ 4.199.900",
    precioSecundario1: "$ 5.399.900",
    descuento: "-28%",
    imagen: "https://media.falabella.com.co/falabellaCO/73354813_01/width=340,height=340,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 11,
    marca: "EPSON",
    nombre: "Impresora Multifuncional Epson EcoTank L3250 Wi-Fi Tinta Continua",
    referencia: "Por TS ONLINE",
    precio: "$ 799.900",
    precioNumero: 799900,
    precioSecundario: "$ 849.900",
    precioSecundario1: "$ 1.099.900",
    descuento: "-25%",
    imagen: "https://media.falabella.com.co/falabellaCO/137155110_01/width=480,height=480,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 12,
    marca: "ACER",
    nombre: "Portátil Acer Aspire 5 Intel Core i5 8GB RAM 512GB SSD 15.6\" Full HD",
    referencia: "Por SENABELLA",
    precio: "$ 1.849.900",
    precioNumero: 1849900,
    precioSecundario: "$ 1.999.900",
    precioSecundario1: "$ 2.599.900",
    descuento: "-30%",
    imagen: "https://media.falabella.com.co/falabellaCO/127619968_01/width=480,height=480,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 13,
    marca: "LOGITECH",
    nombre: "Kit Teclado y Mouse Inalámbrico Logitech MK270 Conexión USB 2.4GHz",
    referencia: "Por SENABELLA",
    precio: "$ 119.900",
    precioNumero: 119900,
    precioSecundario: "$ 139.900",
    precioSecundario1: "$ 159.900",
    descuento: "-20%",
    imagen: "https://media.falabella.com.co/falabellaCO/124164429_01/w=1200,h=1200,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 14,
    marca: "MICROSOFT",
    nombre: "Licencia Microsoft 365 Personal 1 Año Suscripción Digital 1 Usuario",
    referencia: "Por SENABELLA",
    precio: "$ 249.900",
    precioNumero: 249900,
    precioSecundario: "$ 269.900",
    precioSecundario1: "$ 299.900",
    descuento: "-15%",
    imagen: "https://media.falabella.com.co/falabellaCO/73424390_1/w=1200,h=1200,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 15,
    marca: "AMD",
    nombre: "Procesador AMD Ryzen 7 5700G 8 Núcleos 3.8GHz Gráficos Radeon Vega",
    referencia: "Por SENABELLA",
    precio: "$ 899.900",
    precioNumero: 899900,
    precioSecundario: "$ 949.900",
    precioSecundario1: "$ 1.199.900",
    descuento: "-25%",
    imagen: "https://media.falabella.com.co/falabellaCO/73354813_01/width=340,height=340,quality=70,format=webp,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 16,
    marca: "GENERICO",
    nombre: "Soporte de Aluminio Plegable y Ajustable para Portátil y Tablet",
    referencia: "Por SENABELLA",
    precio: "$ 49.900",
    precioNumero: 49900,
    precioSecundario: "$ 59.900",
    precioSecundario1: "$ 89.900",
    descuento: "-40%",
    imagen: "https://media.falabella.com.co/falabellaCO/140922701_01/w=1200,h=1200,fit=pad",
    etiqueta: "CYBER",
  },
  {
    id: 17,
    marca: "JALTECH",
    nombre: "Adaptador Hub USB Type-C 7 en 1 HDMI 4K USB 3.0 Lector de Tarjetas SD",
    referencia: "Por SENABELLA",
    precio: "$ 89.900",
    precioNumero: 89900,
    precioSecundario: "$ 99.900",
    precioSecundario1: "$ 139.900",
    descuento: "-35%",
    imagen: "https://media.falabella.com.co/falabellaCO/155656024_01/w=1200,h=1200,fit=pad",
    etiqueta: "CYBER",
  },
];

export const productosIniciales = productosCatalogo;

// ==========================================
// 3. PRODUCTOS DE ROPA Y ACCESORIOS
// ==========================================
export const productosRopaAccesorios = [
  {
    id: 101,
    marca: "SENABELLA",
    nombre: "Vestido Elegante Mujer Fiesta Estampado Floral Moda Femenina Tallas S-XL",
    categoria: "mujer",
    precio: "$ 129.900",
    precioNumero: 129900,
    precioSecundario: "$ 149.900",
    precioSecundario1: "$ 199.900",
    descuento: "-35%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&auto=format&fit=crop",
  },
  {
    id: 102,
    marca: "SENABELLA",
    nombre: "Chaqueta de Cuero Sintético Hombre Slim Fit Moda Masculina Color Negro",
    categoria: "hombre",
    precio: "$ 189.900",
    precioNumero: 189900,
    precioSecundario: "$ 209.900",
    precioSecundario1: "$ 269.900",
    descuento: "-30%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWgTjtC6eMdbcKiul2_AZgw2fVD3N_Wr1WEJhL0EglBg&s=10",
  },
  {
    id: 103,
    marca: "NIKE",
    nombre: "Tenis Deportivos Hombre Nike Air Max Excee Blancos Calzado Urbano",
    categoria: "calzado",
    precio: "$ 349.900",
    precioNumero: 349900,
    precioSecundario: "$ 379.900",
    precioSecundario1: "$ 469.900",
    descuento: "-25%",
    etiqueta: "CALZADO",
    referencia: "Por SENABELLA SPORT",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsjsSfp0bET8LXZyvw-l8lAViovXcbHb315pM1ty93D3iZ8bc7T8raqqD6&s=10",
  },
  {
    id: 104,
    marca: "ADIDAS",
    nombre: "Tenis Urbano Mujer Adidas Grand Court 2.0 Negros Calzado Deportivo",
    categoria: "calzado",
    precio: "$ 279.900",
    precioNumero: 279900,
    precioSecundario: "$ 299.900",
    precioSecundario1: "$ 349.900",
    descuento: "-20%",
    etiqueta: "CALZADO",
    referencia: "Por SENABELLA SPORT",
    imagen:
      "https://i.pinimg.com/736x/e2/b2/1a/e2b21ac3e2e06a39ad45f77ce6e17613.jpg",
  },
  {
    id: 105,
    marca: "ZARA",
    nombre: "Blusa Casual Mujer Manga Larga Estampado Moderno Talla S-L",
    categoria: "mujer",
    precio: "$ 89.900",
    precioNumero: 89900,
    precioSecundario: "$ 109.900",
    precioSecundario1: "$ 149.900",
    descuento: "-40%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEqA0Sdhk-P-LU_dcaY7GaK9x8e08b7k41_mmTnnnI-w&s=10",
  },
  {
    id: 106,
    marca: "LEVI'S",
    nombre: "Jean Slim Fit Hombre Levi's 511 Azul Oscuro Algodón Premium",
    categoria: "hombre",
    precio: "$ 159.900",
    precioNumero: 159900,
    precioSecundario: "$ 179.900",
    precioSecundario1: "$ 219.900",
    descuento: "-25%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnw1azFfbDwAhHN3GN5N2ElPJHLM_jyYOJTlzyBezRUA&s=10",
  },
  {
    id: 107,
    marca: "PUMA",
    nombre: "Tenis Mujer Puma Carina 2.0 Rosados Plataforma Calzado Urbano",
    categoria: "calzado",
    precio: "$ 249.900",
    precioNumero: 249900,
    precioSecundario: "$ 279.900",
    precioSecundario1: "$ 359.900",
    descuento: "-30%",
    etiqueta: "CALZADO",
    referencia: "Por SENABELLA SPORT",
    imagen: "https://pbs.twimg.com/media/HFp-9iYXgAAJ1-w.jpg",
  },
  {
    id: 108,
    marca: "CONVERSE",
    nombre: "Tenis Converse Chuck Taylor All Star Classic Unisex Canvas Blanco",
    categoria: "calzado",
    precio: "$ 219.900",
    precioNumero: 219900,
    precioSecundario: "$ 239.900",
    precioSecundario1: "$ 279.900",
    descuento: "-20%",
    etiqueta: "CALZADO",
    referencia: "Por SENABELLA SPORT",
    imagen:
      "https://preview.redd.it/my-sister-has-been-wearing-these-converse-for-20-years-v0-3o7kf6t46mwd1.jpg?width=640&crop=smart&auto=webp&s=2b7f878b9b24a12f8bedd1f86f4968c07d0f7b2c",
  },
  {
    id: 109,
    marca: "SENABELLA",
    nombre: "Falda Plisada Midi Mujer Elegante Cintura Alta Color Rosa Blush",
    categoria: "mujer",
    precio: "$ 99.900",
    precioNumero: 99900,
    precioSecundario: "$ 119.900",
    precioSecundario1: "$ 139.900",
    descuento: "-30%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500&auto=format&fit=crop",
  },
  {
    id: 110,
    marca: "SENABELLA",
    nombre: "Camisa Formal Hombre Manga Larga Algodón Slim Fit Azul Cielo",
    categoria: "hombre",
    precio: "$ 79.900",
    precioNumero: 79900,
    precioSecundario: "$ 89.900",
    precioSecundario1: "$ 109.900",
    descuento: "-25%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnDqQqSP84fNnqRcMz9-8BWPGqB54NA0x0oLuH6AzZWQ&s",
  },
  {
    id: 111,
    marca: "MICHAEL KORS",
    nombre: "Reloj Mujer Michael Kors MK5774 Dorado Acero Inoxidable Elegante",
    categoria: "relojes",
    precio: "$ 599.900",
    precioNumero: 599900,
    precioSecundario: "$ 699.900",
    precioSecundario1: "$ 929.900",
    descuento: "-35%",
    etiqueta: "ACCESORIOS",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9k0AXSE_NtuFs28dU7tQaQvSArCackXXm_pWkQZTDYA&s",
  },
  {
    id: 112,
    marca: "SENABELLA",
    nombre: "Mochila Antirrobo USB Impermeable Laptop 15.6\" Viaje Urbano Negra",
    categoria: "accesorios",
    precio: "$ 119.900",
    precioNumero: 119900,
    precioSecundario: "$ 139.900",
    precioSecundario1: "$ 199.900",
    descuento: "-40%",
    etiqueta: "ACCESORIOS",
    referencia: "Por SENABELLA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXyOoSx2cgbgcBw6qOwljz_Kyk40t6Tq3uNMrDKvfwdg&s=10",
  },
  {
    id: 113,
    marca: "ADIDAS",
    nombre: "Sudadera con Capucha Hombre Adidas Essentials 3 Franjas Algodón Gris",
    categoria: "hombre",
    precio: "$ 169.900",
    precioNumero: 169900,
    precioSecundario: "$ 189.900",
    precioSecundario1: "$ 239.900",
    descuento: "-30%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA SPORT",
    imagen:
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&auto=format&fit=crop",
  },
  {
    id: 114,
    marca: "ZARA",
    nombre: "Vestido Casual Mujer Verano Algodón Fresco Estampado Tropical",
    categoria: "mujer",
    precio: "$ 109.900",
    precioNumero: 109900,
    precioSecundario: "$ 129.900",
    precioSecundario1: "$ 149.900",
    descuento: "-25%",
    etiqueta: "MODA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjKdXGl7rnBy90A7PrDWzd2WUlkjIrgmFp2nCPsEW8TA&s=10",
  },
  {
    id: 115,
    marca: "NIKE",
    nombre: "Tenis Running Mujer Nike Revolution 6 Rosados Ligeros Amortiguación",
    categoria: "calzado",
    precio: "$ 299.900",
    precioNumero: 299900,
    precioSecundario: "$ 329.900",
    precioSecundario1: "$ 379.900",
    descuento: "-20%",
    etiqueta: "CALZADO",
    referencia: "Por SENABELLA SPORT",
    imagen: imgZapatos,
  },
  {
    id: 116,
    marca: "SENABELLA",
    nombre: "Look de pareja: Propuesta elegante y romántica para celebraciones",
    categoria: "parejas",
    precio: "$ 359.900",
    precioNumero: 359900,
    precioSecundario: "$ 399.900",
    precioSecundario1: "$ 459.900",
    descuento: "-10%",
    etiqueta: "NUEVO",
    referencia: "Por SENABELLA MODA",
    imagen: imgPareja,
  },
  {
    id: 117,
    marca: "SENABELLA",
    nombre: "Conjunto coordinado moderno con tonos neutros y detalles sofisticados",
    categoria: "parejas",
    precio: "$ 289.900",
    precioNumero: 289900,
    precioSecundario: "$ 329.900",
    precioSecundario1: "$ 389.900",
    descuento: "-20%",
    etiqueta: "OFERTA",
    referencia: "Por SENABELLA MODA",
    imagen: imgCamisa1,
  },
  {
    id: 118,
    marca: "SENABELLA",
    nombre: "Detalle romántico: Texturas suaves y cortes delicados boutique",
    categoria: "parejas",
    precio: "$ 199.900",
    precioNumero: 199900,
    precioSecundario: "$ 239.900",
    precioSecundario1: "$ 279.900",
    descuento: "-15%",
    etiqueta: "EXCLUSIVO",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfCB8hqTQ1Wn98tvM0-H9CBVeWy4dtQ5LsZ92XNsKNbw&s=10",
  },
  {
    id: 119,
    marca: "SENABELLA",
    nombre: "Chaqueta coordinada para Él - Diseño moderno y cómodo",
    categoria: "parejas",
    precio: "$ 189.900",
    precioNumero: 189900,
    precioSecundario: "$ 209.900",
    precioSecundario1: "$ 249.900",
    descuento: "-20%",
    etiqueta: "NUEVO",
    referencia: "Por SENABELLA MODA",
    imagen: imgCamisa2,
  },
  {
    id: 120,
    marca: "SENABELLA",
    nombre: "Chaqueta coordinada para Ella - Diseño romántico y ligero",
    categoria: "parejas",
    precio: "$ 179.900",
    precioNumero: 179900,
    precioSecundario: "$ 199.900",
    precioSecundario1: "$ 239.900",
    descuento: "-20%",
    etiqueta: "NUEVO",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 121,
    marca: "SENABELLA",
    nombre: "Set de camisetas coordinadas para pareja diseño casual",
    categoria: "parejas",
    precio: "$ 129.900",
    precioNumero: 129900,
    precioSecundario: "$ 149.900",
    precioSecundario1: "$ 189.900",
    descuento: "-15%",
    etiqueta: "OFERTA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhFMe-b-ektSfJSGPI-LNVY_ZHq0vd3XEW-l_NKESf1HotP4M3nAECmNA&s=10",
  },
  {
    id: 122,
    marca: "SENABELLA",
    nombre: "Bufandas coordinadas para pareja ideales para el frío",
    categoria: "parejas",
    precio: "$ 89.900",
    precioNumero: 89900,
    precioSecundario: "$ 109.900",
    precioSecundario1: "$ 129.900",
    descuento: "-25%",
    etiqueta: "OFERTA",
    referencia: "Por SENABELLA MODA",
    imagen:
      "https://i.pinimg.com/736x/b5/d5/29/b5d529b50a755b34677a4ea43d781c9d.jpg",
  },
];

export const productosRopa = productosRopaAccesorios;

// ==========================================
// 4. CATEGORÍAS Y MARCAS DE ROPA
// ==========================================
export const categoriasCircularesRopa = [
  {
    titulo: "Moda Mujer",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4j0PMoypc__UeVq6nD4bIh6qFQ4FaGSnEI4GclFl7iw&s=10",
    categoria: "mujer",
  },
  {
    titulo: "Moda Hombre",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWwkq93t5FnksulxA2YfZpSKAUiaqGZ7sNWSgR0wOtoQ&s=10",
    categoria: "hombre",
  },
  {
    titulo: "Calzado",
    imagen:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREmL4kn7HnCXVri8EmYY9FT-MtzgKWj5fhj7F1MvHkRQ&s=10",
    categoria: "calzado",
  },
  {
    titulo: "Accesorios",
    imagen:
      "https://cdn.pixabay.com/photo/2016/06/25/12/48/go-pro-1478810_1280.jpg",
    categoria: "accesorios",
  },
  {
    titulo: "Relojes",
    imagen:
      "https://images.falabella.com/v3/assets/blt088e6fffbba20f16/blt5da4c0580b8c656d/6a59c7bf15befe0a433a8a5a/powercard7_home_relojes_desk.jpg?auto=webp&disable=upscale&quality=70&width=1280",
    categoria: "relojes",
  },
  {
    titulo: "Belleza",
    imagen:
      "https://images.falabella.com/v3/assets/blt088e6fffbba20f16/bltf413d366cc29e9bf/6a5a7cfd5c7ce2611d2d8c44/powercard10_home_belleza_desk.jpg?auto=webp&disable=upscale&quality=70&width=1280",
    categoria: "belleza",
  },
];

export const marcasRopa = [
  "NIKE",
  "ADIDAS",
  "PUMA",
  "ZARA",
  "SENABELLA",
  "MICHAEL KORS",
  "LEVI'S",
  "CONVERSE",
];

export const categoriasListaLateralRopa = [
  "Moda Mujer",
  "Moda Hombre",
  "Calzado",
  "Accesorios",
  "Relojes",
  "Belleza",
];
